# pgadmin:
#   image: dpage/pgadmin4
#   restart: always
#   environment:
#     PGADMIN_DEFAULT_EMAIL: admin@admin.com
#     PGADMIN_DEFAULT_PASSWORD: admin
#   ports:
#     - 5050:80
#   volumes:
#     - pgadmin_data:/var/lib/pgadmin
#   networks:
#     - app

services:
  postgres:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: biplane
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app
    security_opt:
      - label=disable

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app
    security_opt:
      - label=disable
    # command: redis-server --save "" --appendonly no

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    security_opt:
      - label=disable 

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    entrypoint: ["/otelcol-contrib"]
    command: ["--config=/etc/otel-config.yaml"]
    volumes:
      - ./docker/otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"  # OTLP gRPC
      - "4318:4318"  # OTLP HTTP
      - "8889:8889"  # Metrics
    depends_on:
      - tempo
        # condition: service_healthy
      - loki
        # condition: service_healthy
      - prometheus
        # condition: service_healthy
    networks:
      - app
    security_opt:
      - label=disable

  tempo:
    image: grafana/tempo:latest
    command: -config.file=/etc/tempo.yaml
    volumes:
      - ./docker/tempo.yaml:/etc/tempo.yaml
      - tempo_data:/tmp/tempo
    ports:
      - "3200:3200"   # HTTP
      - "4320:4320"    # OTLP gRPC
      - "9095:9095"
      # - "9093:9093"    # gRPC для внутренней коммуникации
    networks:
      - app
    security_opt:
      - label=disable 

  loki:
    image: grafana/loki:latest
    # command: -config.file=/etc/loki/local-config.yaml -validation.allow-structured-metadata=false
    volumes:
      - ./docker/loki-config.yaml:/etc/loki/local-config.yaml
      - loki_data:/var/lib/loki
    ports:
      - "3100:3100"
    networks:
      - app
    security_opt:
      - label=disable

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./docker/prometheus.yaml:/etc/prometheus/prometheus.yml
      - ./docker/prometheus-rules.yaml:/etc/prometheus/prometheus-rules.yaml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - app
    security_opt:
      - label=disable

  node-exporter:
      image: quay.io/prometheus/node-exporter:latest
      ports:
        - "9100:9100"
      command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host/root'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($|/)'
      - '--no-collector.wifi'
      - '--no-collector.hwmon'
      volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/host/root:ro
        - /etc/os-release:/etc/os-release:ro
        - /etc/hostname:/etc/host_hostname:ro
      networks: 
        - app
      security_opt:
        - label=disable
        - seccomp=unconfined
      privileged: true
      environment:
      - "PODMAN_USERNS=keep-id"
      # restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    # build:
      # context: ./docker
      # dockerfile: ./alertmanager.dockerfile
    command:
      # - sh -c 'envsubst < /etc/alertmanager/alertmanager.template.yaml > /etc/alertmanager/alertmanager.yaml && alertmanager --config.file=/etc/alertmanager/alertmanager.yaml'
    # - '/bin/sh'
    # - '-c'
    # - 'envsubst < /etc/alertmanager/alertmanager.template.yaml > /etc/alertmanager/alertmanager.yaml && alertmanager --config.file=/etc/alertmanager/alertmanager.yaml'
      # - -c
      # - "envsubst < /etc/alertmanager/alertmanager.template.yml > /etc/alertmanager/config.yml && /bin/alertmanager --config.file=/etc/alertmanager/config.yml"
      - --config.file=/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    # env_file: .env
    volumes:
      # - ./docker/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
      - ./docker/alertmanager.yaml:/etc/alertmanager/alertmanager.yml
    depends_on:
      - prometheus
    networks:
      - app
    security_opt:
      - label=disable
  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./docker/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana_data:/var/lib/grafana
    ports:
      - "3001:3000"
    depends_on:
      - tempo
      - loki
      - prometheus
      - alertmanager
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app
    security_opt:
      - label=disable 
      
networks:
  app:
    driver: bridge

volumes:
  postgres_data:
  pgadmin_data:
  redis_data:
  rabbitmq_data:
  tempo_data:
  loki_data:
  prometheus_data:
  grafana_data:
