
services:
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: biplane_desing_shop
    ports:
      - 5432:5432
    volumes:
      - .data/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    # volumes:
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - .data/pgadmin_data:/var/lib/pgadmin 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge