receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
  prometheus:
    endpoint: "0.0.0.0:9090"
  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
  otlp/tempo:
    endpoint: "tempo:4320"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo, debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      # prometheusremotewrite:
      #   endpoint: "http://prometheus:9090/api/v1/write"
      exporters: [prometheus, debug] # prometheus сам скрейпит коллектор
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [loki, debug]